[dependencies]
base = "0.11.1"
array = "https://github.com/aviate-labs/array.mo#master@8e4282825d3b401407954917cd94d1548ee21256"
StableTrieMap = "https://github.com/NatLabs/StableTrieMap#master@4781cb03efd34b124c22396c69710b374366c797"
StableBuffer = "https://github.com/canscale/StableBuffer#master@acdde6bb5b939227997cebdbb8919d2e6da8691c"
itertools = "0.2.1"
tecdsa = "0.0.4"
cbor = "0.1.3"
rep-indy-hash = "0.1.1"
libsecp256k1 = "0.1.0"
http-loopback = "0.2.1"
utilities = "2.0.2"